abc:
  network:
  - recertify
  - viewer
  tgw:
  - viewer
architecturesysgroup:
  adc:
  - recertify
  - viewer
  network:
  - viewer
architecturesysgroup1:
  adc:
  - recertify
architecturesysgroup2:
  workflow:
  - recertify
sitao:
  tgw:
  - viewer
