architecturesysgroup:
  adc:
  - recertify
  network:
  - viewer
architecturesysgroup1:
  adc:
  - recertify
architecturesysgroup2:
  workflow:
  - recertify
architecturesysgroup3:
  fi:
  - recertify
